sonar.projectKey=herise-ops_test-devsecops
sonar.projectName=Test DevSecOps
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.js
sonar.sarif.outputReportPaths=sonar.sarif

# Language encoding
sonar.sourceEncoding=UTF-8
sonar.organization=herise-ops
